CREATE TABLE epicuser
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    email      VARCHAR(255),
    avatar_url VARCHAR(255),
    CONSTRAINT pk_epicuser PRIMARY KEY (id)
);

ALTER TABLE epicuser
    ADD CONSTRAINT uc_epicuser_email UNIQUE (email);